services:

  # Databases
  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: academic_db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    networks:
      - gateway-network

  mongo:
    image: mongo:7
    ports:
      - "27017:27017"
    networks:
      - gateway-network

  # Cache
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    networks:
      - gateway-network
  
  # Azure Services
  ## Azure Queue Storage
  azurite:
    image: mcr.microsoft.com/azure-storage/azurite:latest
    ports:
      - "10000:10000"  # Blob
      - "10001:10001"  # Queue
      - "10002:10002"  # Table
    command: azurite-queue --queueHost 0.0.0.0
    networks:
      - gateway-network

  ## Azure APIM
  nginx:
    image: nginx:alpine
    ports:
      - "8000:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - academic-service
      - tasks-service
      - notifications-service
    networks:
      - gateway-network

  ## Azure Functions
  notifications-function:
    build: ../uniflow-notification-function
    environment:
      - AzureWebJobsStorage=DefaultEndpointsProtocol=http;AccountName=devstoreaccount1;AccountKey=Eby8vdM02xNOcqFlqUwJPLlmEtlCDXJ1OUzFT50uSRZ6IFsuFq2UVErCz4I6tq/K1SZFPTOtr/KBHBeksoGMGw==;QueueEndpoint=http://azurite:10001/devstoreaccount1;
      - FUNCTIONS_WORKER_RUNTIME=node
      - NOTIFICATION_SERVICE_URL=http://notifications-service:3003
      - AzureFunctionsJobHost__functionTimeout=00:05:00
      - AzureFunctionsJobHost__Concurrency__SnapshotPersistenceEnabled=false
    ports:
      - "7071:80"
    depends_on:
      - azurite
      - notifications-service
    networks:
      - gateway-network
  # Micro sercices
  academic-service:
    build: ../uniflow-academic-service
    environment:
      - NODE_ENV=development
      - PORT=3001
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/academic_db
      - SPRING_DATASOURCE_USERNAME=admin
      - SPRING_DATASOURCE_PASSWORD=password
      - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
      - GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET}
      - JWT_SECRET=${JWT_SECRET}
      - JWT_EXPIRATION_MS=${JWT_EXPIRATION_MS}
    expose:
      - "3001"
    depends_on:
      - postgres
    networks:
      - gateway-network

  tasks-service:
    build: ../uniflow-tasks-api
    environment:
      - NODE_ENV=development
      - PORT=3002
      - MONGO_URI=mongodb://mongo:27017/tasks_db
      - AZURE_QUEUE_URL=http://azurite:10001/devstoreaccount1
      - AZURE_STORAGE_ACCOUNT=devstoreaccount1
      - AZURE_STORAGE_KEY=Eby8vdM02xNOcqFlqUwJPLlmEtlCDXJ1OUzFT50uSRZ6IFsuFq2UVErCz4I6tq/K1SZFPTOtr/KBHBeksoGMGw==
      - JWT_SECRET=${JWT_SECRET}
    expose:
      - "3002"
    depends_on:
      - mongo
      - azurite
    networks:
      - gateway-network

  notifications-service:
    build: ../uniflow-notification-service
    environment:
      - NODE_ENV=development
      - PORT=3003
      - MONGODB_URI=mongodb://mongo:27017/notifications_db
      - ACADEMIC_SERVICE_URL=http://academic-service:3001
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_TTL=3600
      - REDIS_MAX_ITEMS=100
    expose:
      - "3003"
    depends_on:
      - mongo
      - redis
    networks:
      - gateway-network

networks:
  gateway-network:
    driver: bridge
